import { Video } from '../types';

// S3 base for home screen videos (100x Engineers reels)
const HSV = 'https://aigram-practice-videos-2026.s3.ap-south-1.amazonaws.com/home-screen-videos';

// S3 base for doom-scrolling creator videos
const DSV = 'https://aigram-doomscroll-videos-2026-v2.s3.ap-south-1.amazonaws.com/doom-scrolling';

export const DUMMY_SHORTS_VIDEOS: Video[] = [
  {
    "videoId": "hv_DRemomjiXQ6",
    "title": "100x Engineers — AI Reel 1",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 60,
    "viewCount": 42000,
    "likeCount": 5800,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+1",
    "streamUrl": `${HSV}/hv_DRemomjiXQ6.mp4`,
    "videoUrl": `${HSV}/hv_DRemomjiXQ6.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXJ3sfBCexN",
    "title": "100x Engineers — AI Reel 2",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 58,
    "viewCount": 38000,
    "likeCount": 4900,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:01:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+2",
    "streamUrl": `${HSV}/hv_DXJ3sfBCexN.mp4`,
    "videoUrl": `${HSV}/hv_DXJ3sfBCexN.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXHks47CWof",
    "title": "100x Engineers — AI Reel 3",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 55,
    "viewCount": 35000,
    "likeCount": 4200,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:02:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+3",
    "streamUrl": `${HSV}/hv_DXHks47CWof.mp4`,
    "videoUrl": `${HSV}/hv_DXHks47CWof.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXHTSAjiVKg",
    "title": "100x Engineers — AI Reel 4",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 52,
    "viewCount": 31000,
    "likeCount": 3800,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:03:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+4",
    "streamUrl": `${HSV}/hv_DXHTSAjiVKg.mp4`,
    "videoUrl": `${HSV}/hv_DXHTSAjiVKg.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXExW6hiSs4",
    "title": "100x Engineers — AI Reel 5",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 48,
    "viewCount": 29000,
    "likeCount": 3500,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:04:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+5",
    "streamUrl": `${HSV}/hv_DXExW6hiSs4.mp4`,
    "videoUrl": `${HSV}/hv_DXExW6hiSs4.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXCaHkbiX7E",
    "title": "100x Engineers — AI Reel 6",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 45,
    "viewCount": 27000,
    "likeCount": 3100,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:05:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+6",
    "streamUrl": `${HSV}/hv_DXCaHkbiX7E.mp4`,
    "videoUrl": `${HSV}/hv_DXCaHkbiX7E.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXCLTvQidjm",
    "title": "100x Engineers — AI Reel 7",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 43,
    "viewCount": 25000,
    "likeCount": 2900,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:06:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+7",
    "streamUrl": `${HSV}/hv_DXCLTvQidjm.mp4`,
    "videoUrl": `${HSV}/hv_DXCLTvQidjm.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DW_rCHPie1a",
    "title": "100x Engineers — AI Reel 8",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 40,
    "viewCount": 22000,
    "likeCount": 2600,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:07:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+8",
    "streamUrl": `${HSV}/hv_DW_rCHPie1a.mp4`,
    "videoUrl": `${HSV}/hv_DW_rCHPie1a.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DW9JJPwiT11",
    "title": "100x Engineers — AI Reel 9",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 38,
    "viewCount": 20000,
    "likeCount": 2300,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:08:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+9",
    "streamUrl": `${HSV}/hv_DW9JJPwiT11.mp4`,
    "videoUrl": `${HSV}/hv_DW9JJPwiT11.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DW88nhjCREC",
    "title": "100x Engineers — AI Reel 10",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 36,
    "viewCount": 18000,
    "likeCount": 2100,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:09:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+10",
    "streamUrl": `${HSV}/hv_DW88nhjCREC.mp4`,
    "videoUrl": `${HSV}/hv_DW88nhjCREC.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DW6la-Bidas",
    "title": "100x Engineers — AI Reel 11",
    "description": "AI & tech content by 100x Engineers. Follow on Instagram @100xengineers",
    "authorId": "user_100x_engineers",
    "authorName": "100x Engineers",
    "genre": "AI",
    "tags": ["AI", "100xEngineers", "Tech", "AIgram"],
    "duration": 34,
    "viewCount": 16000,
    "likeCount": 1900,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=100x+Engineers+Reel+11",
    "streamUrl": `${HSV}/hv_DW6la-Bidas.mp4`,
    "videoUrl": `${HSV}/hv_DW6la-Bidas.mp4`,
    "instagramHandle": "100xengineers",
    "linkedinHandle": "",
    "twitterHandle": ""
  },

  // ── Ishaan Sharma — 6 new reels ──────────────────────────────────────────
  {
    "videoId": "hv_DXJ7KcGicXZ",
    "title": "The only 3 AI tools you actually need in 2026",
    "description": "Everyone's overwhelmed by hundreds of AI tools. After testing 200+, these 3 are the only ones that consistently move the needle.",
    "authorId": "user_ishan_sharma",
    "authorName": "Ishan Sharma",
    "genre": "AI",
    "tags": ["AI", "Tools", "Productivity", "AIgram"],
    "duration": 45,
    "viewCount": 87000,
    "likeCount": 9200,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=The+only+3+AI+tools+you+actually+need",
    "streamUrl": `${DSV}/hv_DXJ7KcGicXZ.mp4`,
    "videoUrl": `${DSV}/hv_DXJ7KcGicXZ.mp4`,
    "instagramHandle": "ishansharma7390",
    "linkedinHandle": "ishansharma7390",
    "twitterHandle": "ishansharma7390"
  },
  {
    "videoId": "hv_DW9HXjeiWaM",
    "title": "How I built a 7-figure audience without paid ads",
    "description": "No ads. No influencer deals. Just a repeatable content system that compounds over time. Here's the exact playbook.",
    "authorId": "user_ishan_sharma",
    "authorName": "Ishan Sharma",
    "genre": "AI",
    "tags": ["Growth", "ContentStrategy", "PersonalBrand", "AIgram"],
    "duration": 52,
    "viewCount": 124000,
    "likeCount": 14300,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-26T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=7-figure+audience+without+paid+ads",
    "streamUrl": `${DSV}/hv_DW9HXjeiWaM.mp4`,
    "videoUrl": `${DSV}/hv_DW9HXjeiWaM.mp4`,
    "instagramHandle": "ishansharma7390",
    "linkedinHandle": "ishansharma7390",
    "twitterHandle": "ishansharma7390"
  },
  {
    "videoId": "hv_DW6K2pnCZWV",
    "title": "This ChatGPT prompt saves me 4 hours every day",
    "description": "I've been using this exact prompt structure for 6 months and it has fundamentally changed how fast I work. Here's the template.",
    "authorId": "user_ishan_sharma",
    "authorName": "Ishan Sharma",
    "genre": "AI",
    "tags": ["ChatGPT", "PromptEngineering", "Productivity", "AIgram"],
    "duration": 38,
    "viewCount": 96000,
    "likeCount": 11800,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-25T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=ChatGPT+prompt+saves+4+hours+daily",
    "streamUrl": `${DSV}/hv_DW6K2pnCZWV.mp4`,
    "videoUrl": `${DSV}/hv_DW6K2pnCZWV.mp4`,
    "instagramHandle": "ishansharma7390",
    "linkedinHandle": "ishansharma7390",
    "twitterHandle": "ishansharma7390"
  },
  {
    "videoId": "hv_DW3vdmJCA2w",
    "title": "Why 99% of people are using AI wrong",
    "description": "The problem isn't the AI tool — it's HOW you use it. Most people treat AI like Google search. Here's the right mental model.",
    "authorId": "user_ishan_sharma",
    "authorName": "Ishan Sharma",
    "genre": "AI",
    "tags": ["AI", "MentalModel", "Learning", "AIgram"],
    "duration": 48,
    "viewCount": 152000,
    "likeCount": 18600,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-24T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Why+99%25+are+using+AI+wrong",
    "streamUrl": `${DSV}/hv_DW3vdmJCA2w.mp4`,
    "videoUrl": `${DSV}/hv_DW3vdmJCA2w.mp4`,
    "instagramHandle": "ishansharma7390",
    "linkedinHandle": "ishansharma7390",
    "twitterHandle": "ishansharma7390"
  },
  {
    "videoId": "hv_DWy5bgOiMOz",
    "title": "I made ₹50L using this AI side hustle strategy",
    "description": "No coding required. No team needed. Just one AI workflow that turned my expertise into a scalable income stream.",
    "authorId": "user_ishan_sharma",
    "authorName": "Ishan Sharma",
    "genre": "AI",
    "tags": ["SideHustle", "AI", "Entrepreneurship", "AIgram"],
    "duration": 55,
    "viewCount": 203000,
    "likeCount": 24100,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-23T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Made+%E2%82%B950L+using+AI+side+hustle",
    "streamUrl": `${DSV}/hv_DWy5bgOiMOz.mp4`,
    "videoUrl": `${DSV}/hv_DWy5bgOiMOz.mp4`,
    "instagramHandle": "ishansharma7390",
    "linkedinHandle": "ishansharma7390",
    "twitterHandle": "ishansharma7390"
  },
  {
    "videoId": "hv_DWrPeqziUM3",
    "title": "The uncomfortable truth about building in public",
    "description": "Building in public sounds glamorous. But there's a dark side nobody talks about. Here's what I've learned after 3 years.",
    "authorId": "user_ishan_sharma",
    "authorName": "Ishan Sharma",
    "genre": "AI",
    "tags": ["BuildInPublic", "Entrepreneurship", "Mindset", "AIgram"],
    "duration": 42,
    "viewCount": 78000,
    "likeCount": 9700,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-22T00:10:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Uncomfortable+truth+about+building+in+public",
    "streamUrl": `${DSV}/hv_DWrPeqziUM3.mp4`,
    "videoUrl": `${DSV}/hv_DWrPeqziUM3.mp4`,
    "instagramHandle": "ishansharma7390",
    "linkedinHandle": "ishansharma7390",
    "twitterHandle": "ishansharma7390"
  },

  // ── Vaibhav Sisinty — 11 new reels ───────────────────────────────────────
  {
    "videoId": "hv_DIEc5iVJLKX",
    "title": "The growth hacking secret it took me 5 years to learn",
    "description": "Every growth hack I tried failed until I understood this one principle. This is the framework behind every campaign that actually scaled.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["GrowthHacking", "Marketing", "Startup", "AIgram"],
    "duration": 50,
    "viewCount": 134000,
    "likeCount": 16200,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Growth+hacking+secret+5+years",
    "streamUrl": `${DSV}/hv_DIEc5iVJLKX.mp4`,
    "videoUrl": `${DSV}/hv_DIEc5iVJLKX.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DXHRSyFgY46",
    "title": "Stop boosting posts. Do this instead.",
    "description": "Boosting posts is the biggest waste of money in digital marketing. Here's the exact paid strategy that gets 10x better results for the same budget.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["DigitalMarketing", "PaidAds", "ROI", "AIgram"],
    "duration": 44,
    "viewCount": 98000,
    "likeCount": 11900,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-26T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Stop+boosting+posts.+Do+this+instead.",
    "streamUrl": `${DSV}/hv_DXHRSyFgY46.mp4`,
    "videoUrl": `${DSV}/hv_DXHRSyFgY46.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DXE7d-_goU3",
    "title": "How I get 10x more leads with half the budget",
    "description": "The secret isn't spending more. It's spending smarter. Here's the exact targeting and messaging stack that consistently delivers sub-₹50 CPL.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["LeadGen", "Marketing", "Growth", "AIgram"],
    "duration": 46,
    "viewCount": 117000,
    "likeCount": 13400,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-25T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=10x+more+leads+with+half+the+budget",
    "streamUrl": `${DSV}/hv_DXE7d-_goU3.mp4`,
    "videoUrl": `${DSV}/hv_DXE7d-_goU3.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DXCDTAcAv9e",
    "title": "The email strategy that 10x'd my conversions",
    "description": "I changed one thing in my email sequence and conversions jumped 10x overnight. No new subscribers needed. Just this one psychological trigger.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["EmailMarketing", "Conversion", "CopyWriting", "AIgram"],
    "duration": 48,
    "viewCount": 89000,
    "likeCount": 10700,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-24T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Email+strategy+that+10x%27d+conversions",
    "streamUrl": `${DSV}/hv_DXCDTAcAv9e.mp4`,
    "videoUrl": `${DSV}/hv_DXCDTAcAv9e.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW_kzJYABlZ",
    "title": "The $0 marketing playbook for early-stage founders",
    "description": "You don't need a marketing budget to get your first 1000 customers. Here's the zero-cost channel stack I used to bootstrap two 8-figure businesses.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["Marketing", "Startup", "Bootstrap", "AIgram"],
    "duration": 52,
    "viewCount": 156000,
    "likeCount": 19300,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-23T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=%240+marketing+playbook+for+founders",
    "streamUrl": `${DSV}/hv_DW_kzJYABlZ.mp4`,
    "videoUrl": `${DSV}/hv_DW_kzJYABlZ.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW-2PXBgGCC",
    "title": "The only content strategy you need in 2026",
    "description": "Stop chasing every new platform. This single-channel content strategy generates more qualified leads than any multi-platform approach I've seen.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["ContentStrategy", "Marketing", "Growth", "AIgram"],
    "duration": 40,
    "viewCount": 112000,
    "likeCount": 13100,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-22T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Only+content+strategy+you+need+2026",
    "streamUrl": `${DSV}/hv_DW-2PXBgGCC.mp4`,
    "videoUrl": `${DSV}/hv_DW-2PXBgGCC.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW85mwUg_Mf",
    "title": "Why your startup isn't growing (and how to fix it)",
    "description": "After advising 200+ startups, the growth problem is almost always the same. It's not your product — it's your distribution. Here's how to fix it.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["Startup", "Growth", "Distribution", "AIgram"],
    "duration": 55,
    "viewCount": 178000,
    "likeCount": 21500,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-21T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Why+your+startup+isn%27t+growing",
    "streamUrl": `${DSV}/hv_DW85mwUg_Mf.mp4`,
    "videoUrl": `${DSV}/hv_DW85mwUg_Mf.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW6qDr6A9GE",
    "title": "How to go viral on LinkedIn without paid ads",
    "description": "LinkedIn organic reach is still insane if you know the algorithm triggers. Here are the 5 post formats that get 10x more impressions every single time.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["LinkedIn", "Viral", "ContentMarketing", "AIgram"],
    "duration": 43,
    "viewCount": 143000,
    "likeCount": 17200,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-20T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Go+viral+on+LinkedIn+without+paid+ads",
    "streamUrl": `${DSV}/hv_DW6qDr6A9GE.mp4`,
    "videoUrl": `${DSV}/hv_DW6qDr6A9GE.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW4JAcLgUub",
    "title": "This growth hack generated ₹1 crore in 30 days",
    "description": "One campaign. One insight. One month. Here's the exact growth experiment that generated ₹1 crore in revenue — and how you can replicate it.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["GrowthHack", "Revenue", "CaseStudy", "AIgram"],
    "duration": 58,
    "viewCount": 219000,
    "likeCount": 27600,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-19T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Growth+hack+%E2%82%B91+crore+in+30+days",
    "streamUrl": `${DSV}/hv_DW4JAcLgUub.mp4`,
    "videoUrl": `${DSV}/hv_DW4JAcLgUub.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW3wKReAU77",
    "title": "The marketing funnel nobody talks about",
    "description": "Every marketer knows TOFU-MOFU-BOFU. But the highest-converting companies use a completely different funnel model. Here's what's actually working.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["MarketingFunnel", "Conversion", "Strategy", "AIgram"],
    "duration": 47,
    "viewCount": 102000,
    "likeCount": 12300,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-18T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Marketing+funnel+nobody+talks+about",
    "streamUrl": `${DSV}/hv_DW3wKReAU77.mp4`,
    "videoUrl": `${DSV}/hv_DW3wKReAU77.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },
  {
    "videoId": "hv_DW1UiShMjWZ",
    "title": "The hack top marketers don't want you to know",
    "description": "I paid ₹5L for a marketing masterclass and the most valuable insight was this one counter-intuitive tactic. Sharing it here for free.",
    "authorId": "user_vaibhav_sisinty",
    "authorName": "Vaibhav Sisinty",
    "genre": "AI",
    "tags": ["Marketing", "GrowthHack", "Insider", "AIgram"],
    "duration": 53,
    "viewCount": 168000,
    "likeCount": 20100,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-17T01:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Hack+top+marketers+don%27t+want+you+to+know",
    "streamUrl": `${DSV}/hv_DW1UiShMjWZ.mp4`,
    "videoUrl": `${DSV}/hv_DW1UiShMjWZ.mp4`,
    "instagramHandle": "vaibhavsisinty",
    "linkedinHandle": "",
    "twitterHandle": "vaibhavsisinty"
  },

  // ── Varun Mayya — 5 new reels ─────────────────────────────────────────────
  {
    "videoId": "hv_DXKI64qAclw",
    "title": "AI agents are replacing entire teams. Here's proof.",
    "description": "A team of 3 people with AI agents is now out-executing a traditional team of 30. I've seen it happen across 10 different companies. Here's what changes.",
    "authorId": "user_varun_mayya",
    "authorName": "Varun Mayya",
    "genre": "AI",
    "tags": ["AIAgents", "FutureOfWork", "Automation", "AIgram"],
    "duration": 58,
    "viewCount": 189000,
    "likeCount": 22400,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T02:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=AI+agents+replacing+entire+teams",
    "streamUrl": `${DSV}/hv_DXKI64qAclw.mp4`,
    "videoUrl": `${DSV}/hv_DXKI64qAclw.mp4`,
    "instagramHandle": "thevarunmayya",
    "linkedinHandle": "",
    "twitterHandle": "waitin4agi_"
  },
  {
    "videoId": "hv_DXEvpmwiP0O",
    "title": "How to build an AI startup with zero funding",
    "description": "You don't need VC money to build something meaningful with AI. Here's the exact no-code + AI stack that lets a solo founder compete with funded teams.",
    "authorId": "user_varun_mayya",
    "authorName": "Varun Mayya",
    "genre": "AI",
    "tags": ["AIStartup", "Bootstrap", "NoCode", "AIgram"],
    "duration": 54,
    "viewCount": 143000,
    "likeCount": 17800,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-26T02:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Build+an+AI+startup+with+zero+funding",
    "streamUrl": `${DSV}/hv_DXEvpmwiP0O.mp4`,
    "videoUrl": `${DSV}/hv_DXEvpmwiP0O.mp4`,
    "instagramHandle": "thevarunmayya",
    "linkedinHandle": "",
    "twitterHandle": "waitin4agi_"
  },
  {
    "videoId": "hv_DW_2TufAS89",
    "title": "Everyone's talking about agents. Here's what they miss.",
    "description": "The hype around AI agents is real. But 95% of people building with agents are missing the one thing that makes them actually useful in production.",
    "authorId": "user_varun_mayya",
    "authorName": "Varun Mayya",
    "genre": "AI",
    "tags": ["AIAgents", "LLM", "BuildingWithAI", "AIgram"],
    "duration": 50,
    "viewCount": 167000,
    "likeCount": 19900,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-25T02:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Everyone%27s+talking+about+agents",
    "streamUrl": `${DSV}/hv_DW_2TufAS89.mp4`,
    "videoUrl": `${DSV}/hv_DW_2TufAS89.mp4`,
    "instagramHandle": "thevarunmayya",
    "linkedinHandle": "",
    "twitterHandle": "waitin4agi_"
  },
  {
    "videoId": "hv_DW9FQVKASgg",
    "title": "The future of work is here. Are you prepared?",
    "description": "The skills that made you valuable 3 years ago are being automated. Here's my honest take on what human skills will matter most in an AI-first world.",
    "authorId": "user_varun_mayya",
    "authorName": "Varun Mayya",
    "genre": "AI",
    "tags": ["FutureOfWork", "AI", "Skills", "AIgram"],
    "duration": 60,
    "viewCount": 231000,
    "likeCount": 28700,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-24T02:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Future+of+work+is+here.+Are+you+prepared%3F",
    "streamUrl": `${DSV}/hv_DW9FQVKASgg.mp4`,
    "videoUrl": `${DSV}/hv_DW9FQVKASgg.mp4`,
    "instagramHandle": "thevarunmayya",
    "linkedinHandle": "",
    "twitterHandle": "waitin4agi_"
  },
  {
    "videoId": "hv_DW6r3T9gYrM",
    "title": "I shipped a SaaS in 48 hours using only AI tools",
    "description": "No developers. No designers. Just me, Claude, Cursor, and a no-code deployment stack. Here's the full behind-the-scenes of what I built and how.",
    "authorId": "user_varun_mayya",
    "authorName": "Varun Mayya",
    "genre": "AI",
    "tags": ["SaaS", "IndieHacking", "AITools", "AIgram"],
    "duration": 55,
    "viewCount": 198000,
    "likeCount": 24300,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-23T02:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=SaaS+in+48+hours+using+AI+tools",
    "streamUrl": `${DSV}/hv_DW6r3T9gYrM.mp4`,
    "videoUrl": `${DSV}/hv_DW6r3T9gYrM.mp4`,
    "instagramHandle": "thevarunmayya",
    "linkedinHandle": "",
    "twitterHandle": "waitin4agi_"
  },

  // ── Builders Central — 8 new reels ───────────────────────────────────────
  {
    "videoId": "hv_DXJLpL8kw9V",
    "title": "The fastest way to validate your startup idea",
    "description": "Before you write a single line of code, do this. It takes 48 hours and will save you months of building something nobody wants.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["Startup", "Validation", "ProductMarketFit", "AIgram"],
    "duration": 45,
    "viewCount": 112000,
    "likeCount": 13600,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Fastest+way+to+validate+startup+idea",
    "streamUrl": `${DSV}/hv_DXJLpL8kw9V.mp4`,
    "videoUrl": `${DSV}/hv_DXJLpL8kw9V.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXHudNTE7Ro",
    "title": "How to build a product people actually pay for",
    "description": "The #1 mistake founders make is solving problems that don't hurt enough. Here's the interview framework I use to find genuinely painful problems worth solving.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["ProductBuilding", "CustomerDiscovery", "Startup", "AIgram"],
    "duration": 52,
    "viewCount": 136000,
    "likeCount": 16500,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-26T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Build+a+product+people+actually+pay+for",
    "streamUrl": `${DSV}/hv_DXHudNTE7Ro.mp4`,
    "videoUrl": `${DSV}/hv_DXHudNTE7Ro.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXFPuftE64e",
    "title": "Why 90% of MVPs fail (and how to avoid it)",
    "description": "Most MVPs fail not because of bad execution, but because founders test the wrong hypothesis. Here's how to design an MVP that actually tells you something useful.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["MVP", "ProductStrategy", "Startup", "AIgram"],
    "duration": 48,
    "viewCount": 159000,
    "likeCount": 19200,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-25T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Why+90%25+of+MVPs+fail",
    "streamUrl": `${DSV}/hv_DXFPuftE64e.mp4`,
    "videoUrl": `${DSV}/hv_DXFPuftE64e.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DXEXzmUk2vV",
    "title": "Stop building features nobody asked for",
    "description": "Feature creep kills more startups than competition does. Here's the product prioritisation framework that forces you to only build what truly matters.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["ProductManagement", "Prioritization", "Startup", "AIgram"],
    "duration": 42,
    "viewCount": 127000,
    "likeCount": 15400,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-24T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Stop+building+features+nobody+asked+for",
    "streamUrl": `${DSV}/hv_DXEXzmUk2vV.mp4`,
    "videoUrl": `${DSV}/hv_DXEXzmUk2vV.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DW9gJ6fATSp",
    "title": "From idea to ₹10L ARR in 6 months: the blueprint",
    "description": "Three founders. Three different niches. All hit ₹10L ARR in under 6 months. Here's the common pattern in their go-to-market strategy.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["ARR", "Startup", "GoToMarket", "AIgram"],
    "duration": 60,
    "viewCount": 204000,
    "likeCount": 25800,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-23T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Idea+to+%E2%82%B910L+ARR+in+6+months",
    "streamUrl": `${DSV}/hv_DW9gJ6fATSp.mp4`,
    "videoUrl": `${DSV}/hv_DW9gJ6fATSp.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DW4HcTAk2c1",
    "title": "The one metric that predicts startup success",
    "description": "After studying 500+ startups, one metric predicts survival better than revenue, users, or growth rate. Most founders have never heard of it.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["Metrics", "StartupAdvice", "Growth", "AIgram"],
    "duration": 50,
    "viewCount": 178000,
    "likeCount": 21300,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-22T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=One+metric+that+predicts+startup+success",
    "streamUrl": `${DSV}/hv_DW4HcTAk2c1.mp4`,
    "videoUrl": `${DSV}/hv_DW4HcTAk2c1.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DWzB3ofk-Bi",
    "title": "How builders use AI to ship 10x faster",
    "description": "The builders consistently beating deadlines aren't working harder — they've integrated AI into every step of their workflow. Here's the full process.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["AI", "Productivity", "Shipping", "AIgram"],
    "duration": 47,
    "viewCount": 143000,
    "likeCount": 17600,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-21T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Builders+using+AI+to+ship+10x+faster",
    "streamUrl": `${DSV}/hv_DWzB3ofk-Bi.mp4`,
    "videoUrl": `${DSV}/hv_DWzB3ofk-Bi.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },
  {
    "videoId": "hv_DWx8qBGk1Dt",
    "title": "The build vs buy decision that kills most startups",
    "description": "Should you build your own infra or use third-party tools? Getting this wrong can slow you down for months. Here's the decision framework every founder needs.",
    "authorId": "user_builders_central",
    "authorName": "Builders Central",
    "genre": "AI",
    "tags": ["TechDecisions", "Startup", "Engineering", "AIgram"],
    "duration": 44,
    "viewCount": 98000,
    "likeCount": 11900,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-20T03:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=Build+vs+buy+decision+kills+startups",
    "streamUrl": `${DSV}/hv_DWx8qBGk1Dt.mp4`,
    "videoUrl": `${DSV}/hv_DWx8qBGk1Dt.mp4`,
    "instagramHandle": "builders.central",
    "linkedinHandle": "",
    "twitterHandle": ""
  },

  // ── Ai Ankit Arora — 2 new reels ─────────────────────────────────────────
  {
    "videoId": "hv_DXI-E02EiNy",
    "title": "The AI workflow that replaced my entire content team",
    "description": "I used to have a 5-person content team. Now it's just me and 3 AI agents running 24/7. Here's the exact automation stack I built and how you can copy it.",
    "authorId": "user_ankitarora",
    "authorName": "Ankit Arora",
    "genre": "AI",
    "tags": ["AIWorkflow", "Automation", "ContentTeam", "AIgram"],
    "duration": 55,
    "viewCount": 134000,
    "likeCount": 16800,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-27T04:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=AI+workflow+replaced+my+content+team",
    "streamUrl": `${DSV}/hv_DXI-E02EiNy.mp4`,
    "videoUrl": `${DSV}/hv_DXI-E02EiNy.mp4`,
    "instagramHandle": "ai_ankitarora",
    "twitterHandle": "aiankitarora",
    "linkedinHandle": ""
  },
  {
    "videoId": "hv_DW8GX4qCE75",
    "title": "5 AI tools that will change how you work forever",
    "description": "After testing 100+ AI tools, these 5 have fundamentally changed the way I work. Not just productivity boosts — complete workflow transformations.",
    "authorId": "user_ankitarora",
    "authorName": "Ankit Arora",
    "genre": "AI",
    "tags": ["AITools", "Productivity", "Workflow", "AIgram"],
    "duration": 48,
    "viewCount": 187000,
    "likeCount": 23100,
    "status": "APPROVED",
    "visibility": "PUBLIC",
    "createdAt": "2026-04-26T04:00:00.000Z",
    "thumbnailUrl": "https://via.placeholder.com/540x960?text=5+AI+tools+that+change+how+you+work",
    "streamUrl": `${DSV}/hv_DW8GX4qCE75.mp4`,
    "videoUrl": `${DSV}/hv_DW8GX4qCE75.mp4`,
    "instagramHandle": "ai_ankitarora",
    "twitterHandle": "aiankitarora",
    "linkedinHandle": ""
  }
];

export const generateDummyShorts = (count: number = 5): Video[] => {
  const max = Math.min(count, DUMMY_SHORTS_VIDEOS.length);
  return DUMMY_SHORTS_VIDEOS.slice(0, max);
};
